version: '3.8'

services:
  db:
    image: postgres:15
    container_name: familyhub-db
    env_file:
      - ./env/db.env
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]
    restart: always

volumes:
  db-data:
